### ISSUE TITLE
Simplify the membership application  process

### ISSUE THREAD

**Issue by AndyGaskell** [hackerdeen/articles#4]
I think the membership application is overly complex, in the articles it's described as...

```
Application for membership

16 Any person who wishes to become a member must submit an application for membership, 
along with a remittance to meet the first month’s sub scription; the application will be considered 
by the board.

17 The board may, at its discretion, refuse to admit any person to membership. If membership is 
refused, the first month’s subscription will be returned.

18 The board must notify each applicant promptly (in writing or by e-mail) of its decision on 
whether or not to admit him/her to membership.
```

But it is also documented in the wiki at...
https://wiki.57north.org.uk/doku.php?id=admin:membership_application_process

This is also related to...
#2 Propose membership secretary

**Comment by Hibby** [comment]
@irl was working on a form, which seemed like a good idea. I'm not sure the articles are that far out from where we want to be, apart from maybe the first month in advance thing?

**Comment by AndyGaskell** [comment]
Yea, be nice if we could have a simple form, and just, like, point people to a QR code on the wall, when they asked about joining.

Couple of people asked how to join yesterday.

**Comment by AndyGaskell** [comment]
If we're happy having a google doc for the membership list, then we could set up a form and spreadsheet in 10mins.

**Comment by irl** [comment]
We need to maintain a single register of members. Wherever we put it it should be able to live there for the next 10 years, not have data protection issues and not have cost issues.

I am working on a membership form (it's basically done) that captures the required information and explains the high level obligations of membership. The form includes a section for a proposer. This will be optional but at the AGM we can make that required for application, and as we grow I think it'd be a good thing to add.

The only issue currently in the articles is the first month in advance because we end up having to handle cash. It'd be easier if we just take first payment when they set up the standing order. I don't think it's a huge issue though.

The process on the wiki goes way beyond what is actually required, so more work will be needed in the wiki. Once I've got the finished form ready to publish and use, I'll also go over the wiki.

**Comment by AndyGaskell** [comment]
@irl 
That sounds good, what did you go for, in terms of form implementation and storage format?

Your list of requirements sounds good, I would also add "should not have maintenance issues" also, as such, simplicity is good.

Perhaps 5 years would be a more achievable aim.

**Comment by irl** [comment]
The form is a PDF that you can complete and either email or print. You can also fill in a paper version of it and post it in the Chaos Post mailbox or hand it to a director. Either paper route ends with the form being scanned in. The final destination is the membership secreatary's inbox in all cases.

For the register of members, an excel spreadsheet with a printed copy stored in the file cabinet. (Or latest copy plus paper membership form if it arrived on paper to save excess backup printing).

**Comment by AndyGaskell** [comment]
Paper/PDF sounds good, pretty future proof.  

I'm not so keen on proprietary file formats, used to hate in when HMRC made you fill out the CT600 with Acrobat on Windows.

Is that more or less just the six questions as per...
https://wiki.57north.org.uk/doku.php?id=admin:membership_application_process

It does strike me that the text on the above wiki can be printed or emailed as-is.  What benefits does PDF provide over that?

We (I) still have a the combination code briefcase.  We could us that as a shared secure storage I guess, with directors only knowing the access code.

I always thought, since we use Github already, we could create a private repo for directors' only access, and keep non-puplic info in it, like the members list.  

At the moment this is in Hackhub really I suppose.  I'm not really sure if we use / need hackhub much any-more.

**Comment by AndyGaskell** [comment]
Passed at the AGM, see https://github.com/hackerdeen/meetings/blob/master/2023/2023-04-04_AGM_Minutes.md

PR merged.
